version: "3.9"
services:
  backend:
    image: "rawdagastan/c4s:backend"
    ports:
      - "3000:3000"
 
  frontend:
    environment:
      - VITE_API_ENDPOINT=http://localhost:3000/v1
    image: "mayarosama/cloud4students:latest"
    ports:
       - "8080:80"
