version: "3.9"
services:
  backend:
    image: "rawdagastan/c4s:backend"
    ports:
      - "3000:3000"
 
  # frontend:
  #   environment:
  #     - VUE_APP_BACKEND=ws://localhost:3000/
  #   image: "rawdagastan/c4s:frontend"
  #   ports:
  #     - "8080:8080"