<template>
  <v-container fluid>
    <v-row>
      <v-col cols="12">
        <v-data-table
          :headers="vouchersHeaders"
          :items="vouchers"
          :loading="vouchers.length == 0"
          sort-desc.sync
          class="d-flex justify-center elevation-1"
          :hide-default-footer="vouchers.length == 0"
        >
          <template #[`item.id`]="{ index }"> {{ index + 1 }} </template>

          <template #[`item.name`]="{ item }">
            <div class="d-flex align-center" v-if="item.name">
              <v-avatar color="secondary" size="30" class="mr-2">
                <span class="text-uppercase">{{ userAvatar(item.name) }}</span>
              </v-avatar>
              <div>
                <p>{{ item.name }}</p>
                <p>
                  {{ item.email }}
                </p>
              </div>
            </div>
            <div class="d-flex align-center" v-else>
              <v-avatar color="warning" size="30" class="mr-2">
                <span class="text-uppercase">A</span>
              </v-avatar>
              <div>
                <p>Voucher generated by Admin</p>
              </div>
            </div>
          </template>
          <template #[`item.created_at`]="{ item }">
            {{ timeAgo.format(convertDate(item.created_at)) }}
          </template>
          <template #[`item.updated_at`]="{ item }">
            {{ timeAgo.format(convertDate(item.updated_at)) }}
          </template>

          <template #[`item.reason`]="{ item }">
            {{ item.reason || "-" }}
          </template>

          <template #[`item.balance`]="{ item }">
            {{ item.balance > 0 ? `$${item.balance}` : item.balance }}
          </template>

          <template #[`item.actions`]="{ item }">
            <BaseButton
              v-if="item.rejected"
              variant="text"
              color="error"
              text="Rejected"
              class="mr-1 text-capitalize"
            />
            <BaseButton
              v-else
              variant="text"
              color="success"
              text="Approved"
              class="mr-1 text-capitalize"
            />
          </template>
        </v-data-table>
      </v-col>
    </v-row>
  </v-container>
</template>

<script setup>
import { ref } from "vue";
import TimeAgo from "javascript-time-ago";
import en from "javascript-time-ago/locale/en";
import BaseButton from "@/components/Form/BaseButton.vue";

TimeAgo.addLocale(en);
defineProps({
  vouchers: {
    type: Array,
  },
});

const vouchersHeaders = ref([
  { title: "#", key: "id" },
  { title: "User", key: "name", sortable: false },
  { title: "created at", key: "created_at" },
  { title: "Updated at", key: "updated_at" },
  { title: "Reason for Voucher", key: "reason", sortable: false },
  { title: "Balance", key: "balance" },
  { title: "Voucher", key: "voucher" },
  { title: "Actions", key: "actions", sortable: false },
]);
const timeAgo = ref(new TimeAgo("en-US"));

function userAvatar(name) {
  return name.charAt(0);
}

function convertDate(date) {
  return new Date(date);
}
</script>
