<template>
  <v-container fluid>
    <v-row>
      <v-col cols="12" md="8">
        <v-data-table
          :loading="loading"
          :headers="pendingVouchersHeaders"
          :items="pendingVouchers"
          class="d-flex justify-center elevation-1"
          :hide-default-footer="pendingVouchers == 0"
        >
          <template #[`item.id`]="{ index }"> {{ index + 1 }} </template>

          <template #[`item.name`]="{ item }">
            <div class="d-flex align-center" v-if="item.name">
              <v-avatar color="secondary" size="30" class="mr-2">
                <span class="text-uppercase">{{ userAvatar(item.name) }}</span>
              </v-avatar>
              <div>
                <p>{{ item.name }}</p>
                <p>
                  {{ item.email }}
                </p>
              </div>
            </div>
            <div class="d-flex align-center" v-else>
              <v-avatar color="warning" size="30" class="mr-2">
                <span class="text-uppercase">A</span>
              </v-avatar>
              <div>
                <p>Voucher generated by Admin</p>
              </div>
            </div>
          </template>
          <template #[`item.created_at`]="{ item }">
            {{ timeAgo.format(convertDate(item.created_at)) }}
          </template>
          <template #[`item.balance`]="{ item }">
            {{ item.balance > 0 ? `$${item.balance}` : item.balance }}
          </template>
          <template #[`item.actions`]="{ item }">
            <BaseButton
              color="secondary"
              text="Approve"
              size="small"
              class="mr-1 text-capitalize"
              @click="approveVoucher(item.id, true)"
            />
            <BaseButton
              color="error"
              text="Reject"
              size="small"
              class="text-capitalize"
              @click="approveVoucher(item.id, false)"
            />
          </template>
        </v-data-table>
        <div class="d-flex justify-end">
          <BaseButton
            color="secondary"
            text="Approve All"
            class="my-2"
            :disabled="pendingVouchers > 0"
            @click="approveAllVouchers"
          />
        </div>
      </v-col>
      <v-col cols="12" md="4">
        <v-data-table
          :headers="usersHeaders"
          :items="users"
          class="d-flex justify-center elevation-1"
          :hide-default-footer="users == 0"
        >
          <template #[`item.id`]="{ index }"> {{ index + 1 }} </template>

          <template #[`item.first_name`]="{ item }">
            <div class="d-flex align-center" v-if="item.first_name">
              <v-avatar color="secondary" size="30" class="mr-2">
                <span class="text-uppercase">{{
                  userAvatar(item.first_name)
                }}</span>
              </v-avatar>
              <div>
                <p>{{ item.first_name }}</p>
                <p>
                  {{ item.email }}
                </p>
              </div>
            </div>
            <div v-else>
              <v-avatar color="warning" size="30" class="mr-2">
                <span class="text-uppercase">A</span>
              </v-avatar>
              <div>
                <p>Voucher generated by Admin</p>
              </div>
            </div>
          </template>
          <template #[`item.count.vms`]="{ item }">
            {{ item.count.vms }}
          </template>
          <template #[`item.count.ips`]="{ item }">
            {{ item.count.ips }}
          </template>

          <template #[`item.created_at`]="{ item }">
            <timeago :datetime="item.created_at"></timeago>
          </template>
          <template #[`item.actions`]="{ item }">
            <v-icon class="mr-2">mdi-information</v-icon>
            <v-icon v-if="item.admin" @click="setAdmin(item.email, !item.admin)"
              >mdi-account-key</v-icon
            >
            <v-icon v-else @click="setAdmin(item.email, !item.admin)"
              >mdi-account-lock</v-icon
            >
          </template>
        </v-data-table></v-col
      >
    </v-row>
  </v-container>
  <Toast ref="toast" />
</template>
<script setup>
import { ref, onMounted } from "vue";
import router from "@/router";
import userService from "@/services/userService";
import BaseButton from "@/components/Form/BaseButton.vue";
import Toast from "@/components/Toast.vue";
import TimeAgo from "javascript-time-ago";
import en from "javascript-time-ago/locale/en";
import { storeToRefs } from "pinia";
import { useUserStore } from "@/store/UserStore";

TimeAgo.addLocale(en);
const timeAgo = ref(new TimeAgo("en-US"));
const vouchers = ref([]);
const pendingVouchers = ref([]);
const approveAllCount = ref(0);
const userInfo = ref(null);
const users = ref([]);
const toast = ref(null);
const loading = ref(false);
const store = useUserStore();
const { isAdmin } = storeToRefs(store);

const pendingVouchersHeaders = ref([
  { title: "No", key: "id" },
  { title: "User", key: "name", sortable: false },
  { title: "Created at", key: "created_at" },
  { title: "Reason for Voucher", key: "reason", sortable: false },
  { title: "Balance", key: "balance" },
  { title: "Voucher", key: "voucher" },
  { title: "Actions", key: "actions", sortable: false },
]);

const usersHeaders = ref([
  { title: "No", key: "id", sortable: false },
  { title: "Name", key: "first_name", sortable: false },
  { title: "VMs", key: "count.vms", sortable: false },
  { title: "IPs", key: "count.ips", sortable: false },
  { title: "Actions", key: "actions", sortable: false },
]);

async function getVouchers() {
  loading.value = true;

  try {
    const response = await userService.getVouchers();
    const { data } = response.data;

    approveAllCount.value = 0;

    await updateVouchers(data);

    vouchers.value = data.filter(
      (voucher) => voucher.approved || voucher.rejected
    );
    pendingVouchers.value = data.filter(
      (voucher) => !voucher.approved && !voucher.rejected
    );
  } catch (error) {
    const { err } = error.response.data;
    toast.value.toast(err, "#FF5252");
  } finally {
    loading.value = false;
  }
}

async function updateVouchers(data) {
  const updatePromises = data.map(async (voucher) => {
    await new Promise((resolve) => setTimeout(resolve, 10));

    if (voucher.approved && voucher.rejected) {
      approveAllCount.value++;
    }

    if (users.value && voucher.user_id) {
      userInfo.value = users.value.find((user) => user.ID === voucher.user_id);

      if (userInfo.value && voucher.user_id === userInfo.value.ID) {
        Object.assign(voucher, {
          email: userInfo.value.email,
          name: userInfo.value.first_name,
        });
      }
    }
  });

  await Promise.all(updatePromises);
}

function convertDate(date) {
  return new Date(date);
}

async function getUsers() {
  loading.value = true;
  await userService
    .getUsers()
    .then((response) => {
      const { data } = response.data;
      users.value = data;
    })
    .catch((response) => {
      const { err } = response.response.data;
      toast.value.toast(err, "#FF5252");
    })
    .finally(() => {
      loading.value = false;
    });
}

function userAvatar(name) {
  return name.charAt(0);
}

async function approveVoucher(id, approved) {
  await userService
    .approveVoucher(id, approved)
    .then(async (response) => {
      toast.value.toast(response.data.msg, "#388E3C");
      await getVouchers();
    })
    .catch((response) => {
      const { err } = response.response.data;
      toast.value.toast(err, "#FF5252");
    });
}

async function approveAllVouchers() {
  await userService
    .approveAllVouchers()
    .then(async (response) => {
      toast.value.toast(response.data.msg, "#388E3C");
      await getVouchers();
    })
    .catch((response) => {
      const { err } = response.response.data;
      toast.value.toast(err, "#FF5252");
    });
}

async function setAdmin(email, admin) {
  await userService
    .setAdmin(email, admin)
    .then(async (response) => {
      toast.value.toast(response.data.msg, "#388E3C");
      if (!isAdmin) {
        router.push("/");
      }
      await getUsers();
    })
    .catch((response) => {
      const { err } = response.response.data;
      toast.value.toast(err, "#FF5252");
    });
}

onMounted(async () => {
  await getUsers();
  await getVouchers();
});
</script>
<style>
thead th {
  background-color: #19647e !important;
}
tbody tr {
  background-color: #474747;
}

.v-btn--disabled.bg-error,
.v-btn--disabled.bg-secondary,
.v-btn--disabled.bg-info {
  background-color: transparent !important;
}
</style>
