name: Go lint
on:
  push:
    paths:
      - server/**
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
        id: go

      
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          working-directory: server
          args: --config=.golangci.yml
