name: Go testing

on:
  push:
    paths:
      - server/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
        id: go

      - name: Get dependencies
        run: |
          cd server && go mod download

      - name: Test
        run: cd server && go test -v ./...
