name: Lint
on:
  push:
    paths:
      - client/**

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: client
        run: cd client
      - name: Yarn Install
        run: yarn install
      - name: ESLint
        run: yarn check-eslint
      - name: Prettier
        run: yarn check-prettier
